version: "3"

services:
  server-1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - CORS_ORIGIN=${CORS_ORIGIN}
      - REDIS_URL=${REDIS_URL}

  server-2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - CORS_ORIGIN=${CORS_ORIGIN}
      - REDIS_URL=${REDIS_URL}

  server-3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    environment:
      - PORT=5003
      - CORS_ORIGIN=${CORS_ORIGIN}
      - REDIS_URL=${REDIS_URL}

  caddy:
    image: caddy/caddy:2.7.3-alpine
    container_name: caddy-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
